version: "3"
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  backend:
    build: ./brief-generator-backend
    image: "brief-generator-backend:latest"
    restart: always
    secrets:
      - AWS_S3_SECRET_ACCESS_KEY
      - AWS_S3_ACCESS_KEY_ID
      - AWS_S3_BUCKET_NAME
      - AWS_S3_DOWNLOADS_PATH
      - AWS_S3_REGION
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
  brief-generator-ui:
    build: ./frontend
    image: "brief-generator-ui:latest"
    ports:
      - "80:80"
