version: "3.9"
services:
  frontend:
    build: ./frontend
    image: "brief-generator-frontend:latest"
    ports:
      - "8080:80"
  backend:
    build: ./backend
    image: "brief-generator-backend:latest"
    restart: always
    # secrets:
    #   - AWS_S3_SECRET_ACCESS_KEY
    #   - AWS_S3_ACCESS_KEY_ID
    #   - AWS_S3_BUCKET_NAME
    #   - AWS_S3_DOWNLOADS_PATH
    #   - AWS_S3_REGION
    #   - NEXTAUTH_URL
    #   - NEXTAUTH_SECRET
