version: "3.9"
services:
  frontend:
    build: ./frontend
    image: "brief-generator-frontend:latest"
    ports:
      - "80:80"
  backend:
    build: ./backend
    image: "brief-generator-backend:latest"
    restart: always
