version: "3"
services:
  brief-generator:
    build: ./
    image: "brief-generator:latest"
    restart: always
    ports:
      - "80:3000"
    environment:
      - NEXTAUTH_URL=http://localhost.brief-generator.net
      - NEXTAUTH_SECRET=verysecretsecret
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/brief-generator
