version: "3"
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: ./app
    image: "app:latest"
    restart: always
    environment:
      - DIGITAL_OCEAN_SPACES_SECRET_ACCESS_KEY=s1fWT75Zn11HW+mTLBfsPfPRCMk9CTxguCjTlDr6sT0
      - DIGITAL_OCEAN_SPACES_ACCESS_KEY_ID=X6VQUFXODOYQYJ2XPJAZ
      - DIGITAL_OCEAN_SPACES_BUCKET_NAME=letter-friend
      - DIGITAL_OCEAN_SPACES_DOWNLOADS_PATH=tmp/downloads/
      - DIGITAL_OCEAN_SPACES_ENDPOINT=https://fra1.digitaloceanspaces.com
      - DIGITAL_OCEAN_SPACES_REGION=fra1
      - NEXTAUTH_URL=http://localhost.letterfriend.ezwebs.de
      - NEXTAUTH_SECRET=verysecretsecret
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=letterfriend
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - default
