version: "3"
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  app:
    build: ./app
    image: "app:latest"
    restart: always
    deploy:
      mode: replicated
      replicas: 10
      resources:
        limits:
          cpus: "0.10"
