version: "3"
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
  app:
    build: ./app
    image: "app:latest"
    restart: always
    environment:
      - DATABSE_URL=postgresql://postgres:postgres@localhost/letter-friend
